### ISSUE TITLE
Localhost browser

### ISSUE THREAD

**Issue by eddyaboumansour** [tunerok/unity_browser#10]
Hello, 
Thank you for this plugin I just want to ask how to apply it to a server that is running locally for example Localhost:4200 instead of google for initial URL. and thank you

**Comment by tunerok** [comment]
@eddyaboumansour I'm glad the plugin is helpful to you.  It was in this mode that I used it most of all.  Try entering the local machine address 127.0.0.1, etc.

**Comment by eddyaboumansour** [comment]
Yep I tried 127.0.0.1 and also tried entering my computer's IP address also, but it isn't working.

**Comment by tunerok** [comment]
@eddyaboumansour how are things with the problem?

**Comment by eddyaboumansour** [comment]
It worked, I just commented those two lines in BrowserEngine:
//_localhostname = WWW.EscapeURL(sharedfilename);
//initialURL = RedirectLocalhost(initialURL);
Thank You !
