### ISSUE TITLE
Mouse Click events on a webpage

### ISSUE THREAD

**Issue by eddyaboumansour** [tunerok/unity_browser#11]
Hello, I'm creating a project where I can control the webpage content using hand tracking mouse control. So I'm adding mouse simulations (drag, click....) using the "StandaloneInputModule". The click simulation for example is working with MainUI toolbar, I can click on back and forward using mouse click event simulation. But when working on the content of the webpage like Google Earth I can't control it because it is not set as a RayCast target (clickable events). So my question is where can I find in this plugin the settings for the webpage content, so I can set the content as RayCast target. i added a screenshot for my project's architecture.

![PI - SampleScene - PC, Mac   Linux Standalone - Unity 2020 3 4f1 Personal _DX11_ 4_25_2021 8_49_10 AM (2)](https://user-images.githubusercontent.com/49775809/116006950-c1bb5f00-a60d-11eb-8a6f-a2c0128cc3a8.png)

Thank You.

**Comment by tunerok** [comment]
I think you can find some here

![Screenshot_20210425_232622](https://user-images.githubusercontent.com/20516589/116008551-d869b200-a61d-11eb-9a8f-94fe56fcdd52.jpg)
![Screenshot_20210425_232705](https://user-images.githubusercontent.com/20516589/116008556-dbfd3900-a61d-11eb-85d4-d0c90e4020fe.jpg)

**Comment by eddyaboumansour** [comment]
First thank you I started working with the WebBrowser2D.cs file. And second i figured out the problem in the function TrackerPointer down below, _input is getting confused between my hand pointer and the mouse pointer, and it is always choosing the mouse pointer because the position x,y of the mouse are changing but the position x,y of my hands are not changing. I also created a HandsInputModule that inherits from StandAloneInputModule to process hand gestures and replaced all the StandAloneInputModule in this file with HanddsInputModule. So how to choose the hand pointer and not the mouse pointer as input. 

         IEnumerator TrackPointer()
                {
                  var _raycaster = GetComponentInParent<GraphicRaycaster>();
                  var _input = FindObjectOfType<HandsInputModule>();
                  
            if (_raycaster != null && _input != null && _mainEngine.Initialized)
            {
                while (Application.isPlaying)
                {
                    Vector2 localPos = GetScreenCoords(_raycaster, _input); 
    
                    int px = (int) localPos.x;
                    int py = (int) localPos.y;
              
                    ProcessScrollInput(px, py);

                    if (posX != px || posY != py)
                    {
                        MouseMessage msg = new MouseMessage
                        {
                            Type = MouseEventType.Move,
                            X = px,
                            Y = py,
                            GenericType = MessageLibrary.BrowserEventType.Mouse,
                            // Delta = e.Delta,
                            Button = MouseButton.None
                        };

                        if (Input.GetMouseButton(0))
                            msg.Button = MouseButton.Left;

                        if (Input.GetMouseButton(1))
                            msg.Button = MouseButton.Right;
                                                               
                        if (Input.GetMouseButton(1))
                            msg.Button = MouseButton.Middle;
                           
                        posX = px;
                        posY = py;
                        _mainEngine.SendMouseEvent(msg);
                    }

                    yield return 0;
                }
            }
             // else
             //    UnityEngine.Debug.LogWarning("Could not find GraphicRaycaster and/or HandsInputModule");
        }
