### ISSUE TITLE
Trying to use this to sign into google

### ISSUE THREAD

**Issue by Whiskah** [tunerok/unity_browser#13]
Hello! As above I'm trying to use this to sign into google but on login it says "Cannot sign in, this browser may not be secure" is there anything I can do to make this work?
This is the exact error 
![image](https://user-images.githubusercontent.com/27635588/128339027-26aa9421-f112-48f1-a7f8-8c5273639ccd.png)

**Comment by tunerok** [comment]
This is not possible in this browser.  Google is fighting to protect your account in this way.  This happens with older iPhones too
