### ISSUE TITLE
Copypaste not working

### ISSUE THREAD

**Issue by thaiwash** [tunerok/unity_browser#3]
cannot select text since only clicks get recognized

**Comment by iletai** [comment]
Issues come from Input.GetKey returns a null value when sending char. And enum defines of Unity different. You can see more fore [here](https://docs.unity3d.com/ScriptReference/Input-inputString.html). So to detect it, let handle for special keypress as (dot, backspace..) by sample code:

```
 foreach (KeyCode k in Enum.GetValues(typeof(KeyCode)))
 {
    if (Input.GetKey(code))
    {            if (code == KeyCode.Backspace) // || KeyCode.KeyNeedHandle
                {
                    _mainEngine.SendCharEvent((int)code, KeyEvents.Down);
                }
   }
}
```
