### ISSUE TITLE
Browser2D not working

### ISSUE THREAD

**Issue by wturquaz** [tunerok/unity_browser#4]
Thanks for the package, but Browser2D not work  for me .No error occurs. Does anyone know

**Comment by tunerok** [comment]
Please attach a screenshot of the web browser settings

**Comment by wturquaz** [comment]
I'm so sorry I missed. The initPulugin method in WebBrowser2D.cs should work with StartCoroutine. Problem solved. thanks for the answer

**Comment by tunerok** [comment]
you're welcome
