### ISSUE TITLE
linear color space problem

### ISSUE THREAD

**Issue by hoomanBT** [tunerok/unity_browser#5]
hi 
until stay on gamma color space everything is fine but when i am going to use linear color space browser 2d (raw image) will be too bright and this is happening on both demo scenes . any advice to solve this problem will be appreciated cause its not usable like this .
thank you

**Comment by hoomanBT** [comment]
and this is a screenshot of it
https://ibb.co/hK78JnC

**Comment by tunerok** [comment]
I tried different ways to solve your problem. One of the simplest and fastest was changing the type of the returned texture.

![image](https://user-images.githubusercontent.com/20516589/105975276-d2f0e000-609f-11eb-97b2-4d2e748f37e1.png)

In the BrowserEngine script on line 144, in your case, you need to define a constructor for Texture2D with the parameter linear = false. That is, change the last passed argument to false.


Now it looks like this
![image](https://user-images.githubusercontent.com/20516589/105975727-590d2680-60a0-11eb-9551-45e773bb0cfa.png)

**Comment by tunerok** [comment]
fixed

**Comment by hoomanBT** [comment]
thank you
fixed confirm!
